texts:
  handle_start: "\
    Вот мы и передали вам все неведомые доныне знания Карла Юнга, которые нам \
    удалось заполучить. Если не понимаете, о чем мы — то рекомендуем вам \
    <a href='https://tarotipy.ru/?utm_source=bot'>пройти наш тест</a>. \
    А если уже в курсе, то предлагаем погрузиться в Таротипы еще глубже. И создать собственную карту! \n\n\
    Для этого вам нужно:\n\
    — придумать вашему Таротипу имя\n\
    — подробно описать его личность и характер\n\
    — дать описание его внешности и атрибутов\n\n\
    Никаких ограничений нет — только ваша фантазия, креатив и задор! \n\n\
    Присылайте свой вариант в чат 👇
  "
  handle_draft: "Вы уверены в своем ответе?"
  handle_edit: "Придумали лучше? Отлично! Жду от Вас исправленного варианта👇"
  handle_submit: "\
    Карты благодарят вас! \n\n\
    Результаты конкурса объявим 14 августа — \
    <a href='https://t.me/addlist/dC8VZgOHixxhOTcy'>в каналах студий deza и nomo</a>. \
    Не забудьте подписаться на них, чтобы не пропустить итоги. \
    И не отписывайтесь после розыгрыша — иначе мы вам что-нибудь нагадаем.\n\n\
    А пока ловите небольшой привет от Вселенной: заряженные стикеры и эмоджи. \
    Выбирайте свой вариант — и забирайте по кнопкам ниже.\n\n\
    Не прощаемся — и желаем всего мистического!🃏
  "
  handle_done: "Ваш ответ уже сохранен, спасибо за участие!"
  btn_edit: "🪬 Исправить"
  btn_submit: "🔮 Да"
  btn_emoji1: "Таростикеры"
  btn_emoji2: "Тароэмоджи"
  url_emoji1: "https://t.me/addstickers/tarotipy_stickers"
  url_emoji2: "https://t.me/addemoji/tarotipy_emoji"
