texts:
  handle_start: "\
    Вот мы и передали вам все неведомые доныне знания Карла Юнга, которые нам \
    удалось заполучить. Если не понимаете, о чем мы — то рекомендуем вам пройти наш тест. \
    А если уже в курсе, то предлагаем погрузиться в Таротипы еще глубже. И создать собственную карту! \n\n\
    Для этого вам нужно:\n\
    — придумать вашему Таротипу имя\n\
    — подробно описать его личность и характер\n\
    — дать описание его внешности и атрибутов\n\n\
    Никаких ограничений нет — только ваша фантазия, креатив и задор! \n\n\
    Присылайте свой вариант в чат 👇
  "
  handle_draft: "Вы уверены в своем ответе?"
  handle_edit: "Придумали лучше? Отлично! Жду от Вас исправленного варианта👇"
  handle_submit: "\
    Карты благодарят вас! \n\n\
    Результаты конкурса объявим 14 августа — в каналах студий <a href='https://t.me/dezastudio'>deza</a> \
    и <a href='https://t.me/dvepravki'>nomo</a>. Не забудьте подписаться на них, чтобы не пропустить итоги. \
    И не отписывайтесь после розыгрыша — иначе мы вам что-нибудь нагадаем.\n\n\
    А пока ловите небольшой привет от Вселенной: заряженные стикеры и эмоджи. \
    Выбирайте свой вариант — и забирайте по кнопкам ниже.\n\n\
    Не прощаемся — и желаем всего мистического!🃏
  "
  handle_done: "Ваш ответ уже сохранен, спасибо за участие!"
  btn_edit: "🪬 Нет, хочу исправить"
  btn_submit: "🔮 Да, я уверен"
  btn_emoji1: "Таростикеры — пропитаны харизмой и уверенностью"
  btn_emoji2: "Таромоджи — приносят душевный покой и удачу"
  url_emoji1: "https://t.me/addstickers/HotCherry"
  url_emoji2: "https://t.me/addstickers/HotCherry"
