texts:
  handle_start: "\
    Вот мы и передали вам все неведомые доныне знания Карла Юнга, которые нам \
    удалось заполучить. Думаем, ваша жизнь действительно больше никогда не \
    будет прежней. И не разбрасывайтесь этими знаниями направо и налево — \
    не стоит открывать такое кому попало!\n\n\
    Зато вы можете стать частью нашей с вами тайны.\n\
    Предлагаем вам представить себя на месте Юнга — и <i><b>создать собственного таротипа</b></i>.\n\n\
    <b>Для этого вам нужно</b>:\n\
    - придумать таротипу имя\n\
    - подробно описать его личность и характер\n\
    - и дать описание, как он может выглядеть\n\n\
    Никаких ограничений нет — только ваша фантазия, креатив и задор!\n\n\
    Присылайте свой вариант сюда, в чат👇"
  handle_draft: "\
    Вы уверены? Или хотите что-то подправить?\n\
    ⚠️ <b>После отправки ответа, Вы не сможете его изменить!</b>"
  handle_edit: "\
    Придумали лучше? Отлично! Жду от Вас исправленного варианта👇"
  handle_submit: "\
    Принято!\n\n\
    Карты благодарят вас!\n\
    Рады, если таротипы вам приглянулись. \
    Карл выразил бы вам уважение — и от нас, конечно, тоже большое спасибо за участие. \n\n\
    Результаты конкурса объявим в каналах студий deza (гиперссылка) и nomo (гиперссылка) дд.мм.гг. \
    Не забудьте подписаться на них, чтобы не пропустить итоги. \
    И не отписывайтесь после розыгрыша — иначе мы вам что-нибудь нагадаем.\n\n\
    А пока ждете результатов — почитайте, зачем же, в конце концов, мы достали архивы Карла Юнга \
    и заварили этот проект (готовы спорить, что вам интересно). Ведь ничего не происходит и не \
    делается просто так.\n\n\
    P. S. Чуть не забыли! За участие в конкурсе дарим фирменный набор эмоджи и стикеров. \
    Чтобы светлая карма и высшие Арканы сопровождали вас во всех чатах.\n\n\
    Всего мистического!"
  btn_edit: "🔴 Ещё подумаю..."
  btn_submit: "🟢 Отправляй!"
