texts:
  greeting: "Привет👋 Сосал? Пожалуйста, введите текст заявки."
  success_initial: "Спасибо! Ваш ответ сохранён.\nВы можете изменить его до 35.08.2025 12:00."
  enter_new_text: "Введите новый текст."
  success_update: "Ваш ответ обновлён. Вы можете снова изменить его до 35.08.2025 12:00."
  btn_change: "Изменить ответ"
